### ISSUE TITLE
DoubleDecker does not compile

### ISSUE THREAD

**Issue by piscoroma** [Acreo/DoubleDecker#10]
I'm working at the Politecnico of Turin on a project about the universal node.
So i need to install double decker, but after the last commit, it doesn't compile anymore.
I think there are some problems in the file /include/dd.h.
Actually i'm using the last working version.

**Comment by eponsko** [comment]
Hi! 
Hmm, it compiles here for me, could you paste the errors your are getting?

**Comment by eponsko** [comment]
Ah hmm, okey. Found and fixed the error, locally it was using a different dd.h. The lastest commit should fix the problem.

**Comment by piscoroma** [comment]
Great! Now it works! 
Thank you.
