### ISSUE TITLE
Logging option seems broken

### ISSUE THREAD

**Issue by BtPht** [Acreo/DoubleDecker#11]
The -L option in the broker seems to be broken

`ddbroker -k /etc/doubledecker/broker-keys.json -s 0/0/0 -r tcp://127.0.0.1:5555 -L /tmp/test.log`
`I: (DD) 16-12-09 11:48:23 Setting keys from /etc/doubledecker/broker-keys.json`
`I: (DD) 16-12-09 11:48:23 Broker scope set to: "/0/0/0/"`
`Cannot open logfile (null)`
`Logfile open: Bad address`

**Comment by eponsko** [comment]
Fixed, a ":" was missing from the getopt string
