### ISSUE TITLE
Client name truncated

### ISSUE THREAD

**Issue by BtPht** [Acreo/DoubleDecker#12]
It seems like ddclient is truncating the name given at startup, is it a normal behavior ?

`ddclient -k keys/a-keys.json -d tcp://127.0.0.1:5555 -n abcdefghijklmnopqrst`
`DD initalization ok`
`abcdefghijklmno`

**Comment by eponsko** [comment]
that's weird, I'll have a look

**Comment by eponsko** [comment]
Ah, it's a limitation in ddclient.c, in the generated cli_parser code (cparser_options.h:L51). The maximum length of the prompt is set to 16 bytes including ">>" and \0. We can increase that to say 32 or something, but still truncate the name shown in the CLI, while keeping the actual name used without maximum length. Sounds reasonable?

**Comment by eponsko** [comment]
Fixed now, size upped to 32 bytes, and printing "longnameher..>>" if the name was truncated
