### ISSUE TITLE
C client compiling error

### ISSUE THREAD

**Issue by rbrtbnfgl** [Acreo/DoubleDecker#17]
Compiling the C version the "make" command returns the following error:
undefined reference to `zthread_new'

It results that on the last version of the czmq (https://github.com/zeromq/czmq/blob/master/NEWS#L48) the zthread class is deprecated so the function seems removed.

**Comment by eponsko** [comment]
Hi Roberto, 

Aha, didn't know they had released a version 4, with incompatible ABI. I will have a look into a workaround (I guess we'll have to start checking which version of the library is available). 
A quick fix, that seems to work here, is: 

```
diff --git a/src/lib/client.c b/src/lib/client.c
index ecf36b8..60afbef 100644
--- a/src/lib/client.c
+++ b/src/lib/client.c
@@ -903,7 +903,8 @@ dd_t *dd_new(char *client_name, char *endpoint, char *keyfile, dd_on_con con,
   self->on_data = data;
   self->on_pub = pub;
   self->on_error = error;
-  zthread_new(ddthread, self);
+  //zthread_new(ddthread, self); RETIRED in czmq 4.+
+  zactor_t *actor = zactor_new(dd_actor, self);
   zsys_set_logident("ddclient");
   dd_set_logfp(self, stdout);
   if(getenv("DD_DEBUG") != NULL){

```
I'm not sure if this fix will have any ugly consequences, I think that in your orchestrator you are not actually using this function though.

**Comment by rbrtbnfgl** [comment]
Thank you.
I will try with that fix.
