### ISSUE TITLE
DoubleDecker and IPv6

### ISSUE THREAD

**Issue by BtPht** [Acreo/DoubleDecker#9]
ZMQ supports IPv6 so the DoubleDecker should as well but it's not documented anywhere.

Has it been tested at all ?

**Comment by eponsko** [comment]
Setting ZSYS_IPV6=1 or using the czmq function zsys_set_ipv6() seems to be enough to activate IPv6 support. The issue in DoubleDecker is the validation and generation of the pub/sub ports, which uses  zrex to apply a regular expression and extract matches. The SLRE library that zrex uses seems unable to parse the complex regex needed to validate all possible IPv6 formats. However, we only want to copy the address and capture the last :5555 port specifier, so could skip the validation.

**Comment by eponsko** [comment]
Added support in commit 912f8b28e78124754c39e316f87c90b7aa7951f1
